import os
import uuid
from typing import List
from sqlalchemy.ext.asyncio import AsyncSession
from app.config import settings
from app.core.events import event_bus, DomainEvent
from app.features.reports.models import ReportRecord
from app.features.reports.repository import ReportRepository
from app.features.reports.schemas import ReportGenerateRequest, ReportRecordResponse
from app.core.enums import TimelineEventType


class ReportService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = ReportRepository(db)

    async def generate_report(self, data: ReportGenerateRequest, user_id: str) -> ReportRecordResponse:
        os.makedirs(settings.UPLOAD_DIR, exist_ok=True)
        file_ext = "csv" if data.file_format.upper() == "CSV" else "pdf"
        file_name = f"report_{data.report_type.lower()}_{uuid.uuid4().hex[:8]}.{file_ext}"
        file_path = os.path.join(settings.UPLOAD_DIR, file_name)

        # Write sample report payload file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(f"SCMS Generated Report: {data.report_type}\nFormat: {data.file_format}\nGenerated By: {user_id}\n")

        record = ReportRecord(
            report_type=data.report_type.upper(),
            generated_by_user_id=user_id,
            file_path=file_path,
            file_format=data.file_format.upper(),
            scope_metadata=data.scope_metadata,
        )

        created = await self.repo.save_report_record(record)
        await self.db.commit()

        await event_bus.publish(
            DomainEvent(
                type=TimelineEventType.REPORT_GENERATED.value,
                actor_id=user_id,
                metadata={"report_id": str(created.id), "type": created.report_type},
            )
        )

        return ReportRecordResponse.model_validate(created)

    async def list_reports(self, user_id: str) -> List[ReportRecordResponse]:
        records = await self.repo.list_user_reports(user_id)
        return [ReportRecordResponse.model_validate(r) for r in records]
