from enum import Enum


class UserRole(str, Enum):
    STUDENT = "STUDENT"
    COUNSELLOR = "COUNSELLOR"
    FACULTY = "FACULTY"
    HOD = "HOD"
    ADMIN = "ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"


class StudentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    GRADUATED = "GRADUATED"
    DROPPED = "DROPPED"
    TRANSFERRED = "TRANSFERRED"


class AttendanceStatus(str, Enum):
    PRESENT = "PRESENT"
    ABSENT = "ABSENT"
    ON_DUTY = "ON_DUTY"
    MEDICAL_LEAVE = "MEDICAL_LEAVE"


class RiskLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FollowUpStatus(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    OVERDUE = "OVERDUE"


class SessionType(str, Enum):
    ACADEMIC = "ACADEMIC"
    PERSONAL = "PERSONAL"
    BEHAVIOURAL = "BEHAVIOURAL"
    CAREER = "CAREER"
    HEALTH = "HEALTH"
    FINANCIAL = "FINANCIAL"


class SessionMode(str, Enum):
    IN_PERSON = "IN_PERSON"
    PHONE = "PHONE"
    VIDEO_CALL = "VIDEO_CALL"


class CommunicationMode(str, Enum):
    PHONE_CALL = "PHONE_CALL"
    IN_PERSON = "IN_PERSON"
    EMAIL = "EMAIL"
    VIDEO_CALL = "VIDEO_CALL"


class CommunicationOutcome(str, Enum):
    POSITIVE = "POSITIVE"
    NEUTRAL = "NEUTRAL"
    CONCERNING = "CONCERNING"
    UNRESPONSIVE = "UNRESPONSIVE"


class BacklogStatus(str, Enum):
    ACTIVE = "ACTIVE"
    CLEARED = "CLEARED"


class NotificationPriority(str, Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"


class NotificationType(str, Enum):
    ATTENDANCE_ALERT = "ATTENDANCE_ALERT"
    FOLLOW_UP_REMINDER = "FOLLOW_UP_REMINDER"
    SESSION_CREATED = "SESSION_CREATED"
    APPROVAL_REQUEST = "APPROVAL_REQUEST"
    BROADCAST = "BROADCAST"
    SYSTEM = "SYSTEM"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class TimelineEventType(str, Enum):
    STUDENT_REGISTERED = "STUDENT_REGISTERED"
    STUDENT_STATUS_CHANGED = "STUDENT_STATUS_CHANGED"
    STUDENT_PROMOTED = "STUDENT_PROMOTED"
    COUNSELLOR_ASSIGNED = "COUNSELLOR_ASSIGNED"
    COUNSELLOR_REASSIGNED = "COUNSELLOR_REASSIGNED"
    ATTENDANCE_UPDATED = "ATTENDANCE_UPDATED"
    ATTENDANCE_BELOW_THRESHOLD = "ATTENDANCE_BELOW_THRESHOLD"
    ATTENDANCE_CRITICAL = "ATTENDANCE_CRITICAL"
    MARKS_UPDATED = "MARKS_UPDATED"
    SGPA_CALCULATED = "SGPA_CALCULATED"
    BACKLOG_ADDED = "BACKLOG_ADDED"
    BACKLOG_CLEARED = "BACKLOG_CLEARED"
    SESSION_CONDUCTED = "SESSION_CONDUCTED"
    SESSION_ACKNOWLEDGED = "SESSION_ACKNOWLEDGED"
    FOLLOW_UP_CREATED = "FOLLOW_UP_CREATED"
    FOLLOW_UP_COMPLETED = "FOLLOW_UP_COMPLETED"
    FOLLOW_UP_OVERDUE = "FOLLOW_UP_OVERDUE"
    PARENT_COMMUNICATION = "PARENT_COMMUNICATION"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    RISK_FLAG_CHANGED = "RISK_FLAG_CHANGED"
    REPORT_GENERATED = "REPORT_GENERATED"
