export enum UserRole {
  STUDENT = "STUDENT",
  COUNSELLOR = "COUNSELLOR",
  FACULTY = "FACULTY",
  HOD = "HOD",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN"
}

export enum StudentStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  GRADUATED = "GRADUATED",
  DROPPED = "DROPPED",
  TRANSFERRED = "TRANSFERRED"
}

export enum AttendanceStatus {
  PRESENT = "PRESENT",
  ABSENT = "ABSENT",
  ON_DUTY = "ON_DUTY",
  MEDICAL_LEAVE = "MEDICAL_LEAVE"
}

export enum RiskLevel {
  NONE = "NONE",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL"
}

export enum FollowUpStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  OVERDUE = "OVERDUE"
}

export enum SessionType {
  ACADEMIC = "ACADEMIC",
  PERSONAL = "PERSONAL",
  BEHAVIOURAL = "BEHAVIOURAL",
  CAREER = "CAREER",
  HEALTH = "HEALTH",
  FINANCIAL = "FINANCIAL"
}

export enum SessionMode {
  IN_PERSON = "IN_PERSON",
  PHONE = "PHONE",
  VIDEO_CALL = "VIDEO_CALL"
}

export enum CommunicationMode {
  PHONE_CALL = "PHONE_CALL",
  IN_PERSON = "IN_PERSON",
  EMAIL = "EMAIL",
  VIDEO_CALL = "VIDEO_CALL"
}

export enum CommunicationOutcome {
  POSITIVE = "POSITIVE",
  NEUTRAL = "NEUTRAL",
  CONCERNING = "CONCERNING",
  UNRESPONSIVE = "UNRESPONSIVE"
}

export enum BacklogStatus {
  ACTIVE = "ACTIVE",
  CLEARED = "CLEARED"
}

export enum NotificationPriority {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  URGENT = "URGENT"
}

export enum ApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED"
}

export enum DocumentCategory {
  PROFILE_PHOTO = "PROFILE_PHOTO",
  CERTIFICATE = "CERTIFICATE",
  FEE_RECEIPT = "FEE_RECEIPT",
  MEDICAL = "MEDICAL",
  OTHER = "OTHER"
}

export enum TimelineEventType {
  STUDENT_REGISTERED = "STUDENT_REGISTERED",
  STUDENT_STATUS_CHANGED = "STUDENT_STATUS_CHANGED",
  STUDENT_PROMOTED = "STUDENT_PROMOTED",
  COUNSELLOR_ASSIGNED = "COUNSELLOR_ASSIGNED",
  COUNSELLOR_REASSIGNED = "COUNSELLOR_REASSIGNED",
  ATTENDANCE_UPDATED = "ATTENDANCE_UPDATED",
  ATTENDANCE_BELOW_THRESHOLD = "ATTENDANCE_BELOW_THRESHOLD",
  ATTENDANCE_CRITICAL = "ATTENDANCE_CRITICAL",
  MARKS_UPDATED = "MARKS_UPDATED",
  SGPA_CALCULATED = "SGPA_CALCULATED",
  BACKLOG_ADDED = "BACKLOG_ADDED",
  BACKLOG_CLEARED = "BACKLOG_CLEARED",
  SESSION_CONDUCTED = "SESSION_CONDUCTED",
  SESSION_ACKNOWLEDGED = "SESSION_ACKNOWLEDGED",
  FOLLOW_UP_CREATED = "FOLLOW_UP_CREATED",
  FOLLOW_UP_COMPLETED = "FOLLOW_UP_COMPLETED",
  FOLLOW_UP_OVERDUE = "FOLLOW_UP_OVERDUE",
  PARENT_COMMUNICATION = "PARENT_COMMUNICATION",
  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
  RISK_FLAG_CHANGED = "RISK_FLAG_CHANGED",
  REPORT_GENERATED = "REPORT_GENERATED"
}

export enum NotificationType {
  ATTENDANCE_ALERT = "ATTENDANCE_ALERT",
  FOLLOW_UP_REMINDER = "FOLLOW_UP_REMINDER",
  SESSION_CREATED = "SESSION_CREATED",
  APPROVAL_REQUEST = "APPROVAL_REQUEST",
  BROADCAST = "BROADCAST",
  SYSTEM = "SYSTEM"
}

export enum AuditAction {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  ARCHIVE = "ARCHIVE",
  RESTORE = "RESTORE",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  EXPORT = "EXPORT",
  APPROVE = "APPROVE",
  REJECT = "REJECT"
}
