from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# --------------------------------------------------------------------------
# Step 2 — Preview
# --------------------------------------------------------------------------

class DetectedColumn(BaseModel):
    field: str
    source_header: str
    label: str


class DetectedRange(BaseModel):
    row_number: int
    raw_text: str
    description: str
    student_count: int
    counsellor_name: Optional[str] = None
    counsellor_phone: Optional[str] = None
    first_roll: Optional[str] = None
    last_roll: Optional[str] = None
    warnings: List[str] = Field(default_factory=list)
    errors: List[str] = Field(default_factory=list)


class DetectedCounsellor(BaseModel):
    key: str
    name_as_written: str
    display_name: str
    phone: Optional[str] = None
    email: Optional[str] = None
    proposed_username: Optional[str] = None
    student_count: int
    # NEW when no account matches, EXISTING when one will be reused.
    status: str
    existing_user_id: Optional[str] = None
    matched_on: Optional[str] = None
    rows: List[int] = Field(default_factory=list)


class DuplicateStudent(BaseModel):
    roll_number: str
    reason: str
    existing_name: Optional[str] = None
    row_numbers: List[int] = Field(default_factory=list)


class FieldSuggestion(BaseModel):
    """One value the Configure step needs, with whatever the file implied."""

    field: str
    label: str
    required: bool
    source: str  # FILE | DERIVED | CURRENT | NONE
    detected_value: Optional[str] = None
    detected_id: Optional[str] = None
    confidence: str  # HIGH | MEDIUM | NONE
    note: Optional[str] = None


class ImportPreviewResponse(BaseModel):
    batch_id: str
    file_name: str
    sheet_name: str
    header_row_number: int
    status: str

    detected_columns: List[DetectedColumn]
    ignored_columns: List[str]

    total_rows: int
    valid_rows: int
    students_detected: int
    counsellors_detected: int
    new_counsellors: int
    existing_counsellors: int
    duplicate_students: int
    importable_students: int

    ranges: List[DetectedRange]
    counsellors: List[DetectedCounsellor]
    duplicates: List[DuplicateStudent]
    suggestions: List[FieldSuggestion]
    warnings: List[str]
    errors: List[str]
    sample_roll_numbers: List[str]


# --------------------------------------------------------------------------
# Step 3 — Configure / Step 4 — Import
# --------------------------------------------------------------------------

class ImportConfiguration(BaseModel):
    """The values applied to every student generated by this import.

    Everything is an existing catalog entry chosen by name — the administrator
    never types or pastes an identifier. Sections are the one exception: they
    are created on demand, because a new intake's sections rarely exist yet.
    """

    department_id: str = Field(..., description="Department chosen from Academic Configuration")
    semester_id: str = Field(..., description="Semester chosen from the fixed 1-1..4-2 catalog")
    section_name: str = Field(..., min_length=1, max_length=20, description="e.g. A — created if absent")
    batch_year: int = Field(..., ge=2000, le=2100)
    academic_year_id: Optional[str] = None
    study_year: Optional[int] = Field(None, ge=1, le=4)
    # Off by default: re-importing a corrected sheet must never silently
    # overwrite a counsellor assignment an administrator set by hand.
    reassign_existing_students: bool = False


class ImportProgressResponse(BaseModel):
    batch_id: str
    status: str
    phase: str
    phase_label: str
    percent: int
    processed: int
    total: int
    message: Optional[str] = None
    error: Optional[str] = None


# --------------------------------------------------------------------------
# Step 5 — Completed
# --------------------------------------------------------------------------

class ImportRecordResult(BaseModel):
    record_type: str
    identifier: str
    display_name: Optional[str] = None
    status: str
    message: Optional[str] = None
    source_row_number: Optional[int] = None

    class Config:
        from_attributes = True


class GeneratedCredential(BaseModel):
    record_type: str
    identifier: str
    full_name: str
    username: str
    email: str
    temporary_password: str
    counsellor: Optional[str] = None
    status: str = "Active"


class ImportSummaryResponse(BaseModel):
    batch_id: str
    file_name: str
    status: str
    imported_by: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None

    total_rows: int
    students_detected: int
    counsellors_detected: int
    students_created: int
    students_skipped: int
    counsellors_created: int
    counsellors_reused: int
    assignments_created: int
    failed_records: int
    warning_count: int
    error_message: Optional[str] = None

    configuration: Optional[Dict[str, Any]] = None
    credentials_available: bool = False
    credential_count: int = 0
    records: List[ImportRecordResult] = Field(default_factory=list)


class ImportHistoryItem(BaseModel):
    batch_id: str
    file_name: str
    status: str
    imported_by: Optional[str] = None
    created_at: datetime
    completed_at: Optional[datetime] = None
    students_created: int
    counsellors_created: int
    students_skipped: int
    failed_records: int
    credentials_available: bool


class ImportHistoryResponse(BaseModel):
    items: List[ImportHistoryItem]
    total_imports: int
    completed_imports: int
    total_students_created: int
    total_counsellors_created: int
    success_rate: float
    last_import_at: Optional[datetime] = None
